### ISSUE TITLE
Markbot Doesn't Like My Display

### ISSUE THREAD

**Issue by drew0036** [drew0036/components-on-a-grid#1]
Hey @mackenzierose

I got the repository to be within a 3% difference, but no matter what I put, Markbot doesn't like my display. It only looks right using grid or inline-grid. Can you please take a look at my code? 

Thank you for your advice!
- Holly

![Screen Shot 2020-09-09 at 9 22 01 PM](https://user-images.githubusercontent.com/55107709/92672770-79059e80-f2e7-11ea-9809-98c571d0ce64.png)

![Screen Shot 2020-09-09 at 10 02 23 PM](https://user-images.githubusercontent.com/55107709/92673086-44461700-f2e8-11ea-8772-2af4585e2074.png)

![Screen Shot 2020-09-09 at 10 02 30 PM](https://user-images.githubusercontent.com/55107709/92673090-460fda80-f2e8-11ea-8c41-ca9003c6bf2a.png)

**Comment by MacKenzieRose** [comment]
Hey @drew0036 

Markbot is looking for a display of "contents" inside of the header element, which dramatically changes your screenshots. This is a cool feature that gets rid of the div box, so children elements are on the same level of hierarchy as the box-less parent.

However, you'll see this completely changes your screenshots; if you need help fixing them, let me know 😸 

MacKenzie

**Comment by drew0036** [comment]
Yay, of course it changes everything, haha, thank you! ^___^
